export const UFC_DATA_FILTER_DATE = 'UFC_DATA_FILTER_DATE';
export const UFC_DATA_FILTER_LOCATION = 'UFC_DATA_FILTER_LOCATION';
export const UFC_DATA_FILTER_FIGHTER = 'UFC_DATA_FILTER_FIGHTER';
export const UFC_RESET_FILTER = 'UFC_RESET_FILTER';
export const UFC_FILTER_DATA = 'UFC_FILTER_DATA';
